app = "nebuladuel"

[build]
image = "registry.fly.io/nebuladuel"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 900000000000000000
hard_limit = 950000000000000000
SM_DEADLINE_CHECKIN = "360000000000"

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "performance-2x"
memory = "4gb"
SM_DEADLINE_CHECKIN = "360000000000"
NODE_OPTIONS='--max-old-space-size=4096'
overcommit_memory = 1

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "84532"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0x717253d98687f16a1348fB495b1AC7759B6940c8"
CARTESI_CONTRACTS_APPLICATION_DEPLOYMENT_BLOCK_NUMBER = "11965606"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0x0F4A95D7fA5211cAFfB9ddbb5c692a89cEA94789"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0xD52eFe632A2F19C18B955B075195495dbC783750"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "8688714"
CARTESI_EPOCH_DURATION = "86400"
SM_DEADLINE_CHECKIN = "360000000000"
NODE_OPTIONS='--max-old-space-size=4096'
OVERCOMMIT_MEMORY = "1"
