app = "nebuladuel"

[build]
image = "registry.fly.io/nebuladuel"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 200000
hard_limit = 250000
timeout = "500s"


[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "500s"
path = "/healthz"

[[vm]]
size = "shared-cpu-1x"
memory = "2gb"

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "84532"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0xE70Ab4A56e8D83e50c0Da2434FB5Aa6e0A0cAf0C"
CARTESI_CONTRACTS_APPLICATION_DEPLOYMENT_BLOCK_NUMBER = "11697132"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0x0229b1B976eC1C56D0f8c2985218c244874166dc"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0xf40b437B0e1b602772dC134C92Bc9E1a7771E2e1"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "8688714"
CARTESI_EPOCH_DURATION = "86400"

