app = "nebuladuel"

[build]
image = "registry.fly.io/nebuladuel"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 900000000000000000
hard_limit = 950000000000000000
SM_DEADLINE_CHECKIN = "360000000000"

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "performance-4x"
memory = "8gb"
SM_DEADLINE_CHECKIN = "360000000000"
NODE_OPTIONS='--max-old-space-size=4096'
overcommit_memory = 1
OVERCOMMIT_MEMORY = 1

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "84532"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0x247a62A6B93DC2dFaAEaba1f4C488B23f7390c4b"
CARTESI_CONTRACTS_APPLICATION_DEPLOYMENT_BLOCK_NUMBER = "12002290"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0x2009F6799625C3Cd5661c38380fFd01D534B3d60"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0x33e1ad5bc91C62F2DD365eC2db2025c4628CBf92"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "8688714"
CARTESI_EPOCH_DURATION = "86400"
SM_DEADLINE_CHECKIN = "360000000000"
NODE_OPTIONS='--max-old-space-size=4096'
OVERCOMMIT_MEMORY = "1"
