app = "nebuladuel"

[build]
image = "registry.fly.io/nebuladuel"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 900000000000000000
hard_limit = 950000000000000000

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "performance-2x"
memory = "4gb"
NODE_OPTIONS='--max-old-space-size=4096'
overcommit_memory = 1



[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "84532"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0xfC00C430341132E5b6333Fdb9Dec4e141d9E9Faa"
CARTESI_CONTRACTS_APPLICATION_DEPLOYMENT_BLOCK_NUMBER = "11912347"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0xD4d8784E86Ad84a25c7348F00A0d9C2466bE2Abc"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0x1DaA7987b6F46Cd929f6c02A686700ed0Af1d1dA"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "8688714"
CARTESI_EPOCH_DURATION = "86400"
NODE_OPTIONS='--max-old-space-size=4096'
OVERCOMMIT_MEMORY = "1"

