app = "nebuladuel"

[build]
image = "registry.fly.io/nebuladuel"

[http_service]
internal_port = 10000
force_https = true

[http_service.concurrency]
type = "requests"
soft_limit = 900000000000000000
hard_limit = 950000000000000000


[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthz"

[[vm]]
size = "performance-2x"
memory = "4gb"

[env]
CARTESI_BLOCKCHAIN_FINALITY_OFFSET = "1"
CARTESI_BLOCKCHAIN_ID = "84532"
CARTESI_CONTRACTS_APPLICATION_ADDRESS = "0xf84758459f89CffB2cC9928b04d8bDf50292777c"
CARTESI_CONTRACTS_APPLICATION_DEPLOYMENT_BLOCK_NUMBER = "11929232"
CARTESI_CONTRACTS_AUTHORITY_ADDRESS = "0x4caCcCB1b3c1c3Cf45c8A76E703BA434850c776E"
CARTESI_CONTRACTS_HISTORY_ADDRESS = "0xcAfDA8171Aa7e174AC91F6C9590fF40aD3E5a4ee"
CARTESI_CONTRACTS_INPUT_BOX_ADDRESS = "0x59b22D57D4f067708AB0c00552767405926dc768"
CARTESI_CONTRACTS_INPUT_BOX_DEPLOYMENT_BLOCK_NUMBER = "8688714"
CARTESI_EPOCH_DURATION = "86400"
