const data = [
    {
        id: 1,
        name: "Godzilla",
        img: "./assets/img/Godzilla.png",
        health: 80,
        strength: 8,
        attack: 15,
        speed: 10,
        superPower: "Thunderbolt",
        totalWins: 270,
        totalLoss: 0,
        profileImg: "./assets/img/Godzilla.png",
        price: 270,
        owner: ""        
    },
    {
        id: 2,
        name: "Dragon",
        img: "./assets/img/Dragon.png", 
        health: 95,
        strength: 10,
        attack: 13,
        speed: 7,
        superPower: "Flamethrower",
        totalWins: 390,
        totalLoss: 0,
        profileImg: "./assets/img/Dragon.png",
        price: 390,
        owner: "" 
    },
    {
        id: 3,
        name: "Komodo", 
        img: "./assets/img/komodo.png", 
        health: 60,
        strength: 5,
        attack: 10,
        speed: 8,
        superPower: "Vine Whip",
        totalWins: 250,
        totalLoss: 0,
        profileImg: "./assets/img/komodo.png",
        price: 250,
        owner: "" 
    },
    {
        id: 4,
        name: "IceBeever", 
        img: "./assets/img/IceBeever.png", 
        health: 90,
        strength: 10,
        attack: 16,
        speed: 9,
        superPower: "Water Gun",
        totalWins: 380,
        totalLoss: 0,
        profileImg: "./assets/img/IceBeever.png",
        price: 380,
        owner: "" 
    },
    {
        id: 5,
        name: "KomodoDragon", 
        img: "./assets/img/KomodoDragon.png",
        health: 75,
        strength: 7,
        attack: 13,
        speed: 9,
        superPower: "Sleep Song",
        totalWins: 300,
        totalLoss: 0,
        profileImg: "./assets/img/KomodoDragon.png",
        price: 300,
        owner: "" 
    },
    {
        id: 6,
        name: "Fox", 
        img: "./assets/img/Fox.png",
        health: 90,
        strength: 12,
        attack: 16,
        speed: 6,
        superPower: "Psychic",
        totalWins: 380,
        totalLoss: 0,
        profileImg: "./assets/img/Fox.png",
        price: 380,
        owner: "" 
    },
    {
        id: 7,
        name: "Hound", 
        img: "./assets/img/Hound.png",
        health: 100,
        strength: 11,
        attack: 15,
        speed: 7,
        superPower: "Adaptability",
        totalWins: 410,
        totalLoss: 0,
        profileImg: "./assets/img/Hound.png",
        price: 410,
        owner: "" 
    },
    {
        id: 8,
        name: "Rhyno", 
        img: "./assets/img/Rhyno.png",
        health: 100,
        strength: 12,
        attack: 15,
        speed: 6,
        superPower: "Shadow Ball",
        totalWins: 420,
        totalLoss: 0,
        profileImg: "./assets/img/Rhyno.png",
        price: 420,
        owner: ""
    }
]

export default data;