const data = [
    {
        duelId: 1,
        isActive: true,
        stake: "400",
        isCompleted: false,
        duelCreator: 'Nonso',
        avatar: "./assets/img/Rhyno.png",
        duelParticipant: '',
        creatorWarriors: [],
        participantWarriors: [],
        creatorStrategy: '',
        participantStrategy: '',
        battleLog: [],
        duelWinner: "",
        duelLoser: ""        
    },
    {
        duelId: 2,
        isActive: true,
        stake: "200",
        isCompleted: false,
        duelCreator: 'Nicki',
        avatar: "./assets/img/Rhyno.png",
        duelParticipant: 'Vigo',
        creatorWarriors: [],
        participantWarriors: [],
        creatorStrategy: '',
        participantStrategy: '',
        battleLog: [],
        duelWinner: "",
        duelLoser: ""     
    },
    {
        duelId: 3,
        isActive: true,
        stake: "1000",
        isCompleted: false,
        duelCreator: 'Imma',
        avatar: "./assets/img/Rhyno.png",
        duelParticipant: '',
        creatorWarriors: [],
        participantWarriors: [],
        creatorStrategy: '',
        participantStrategy: '',
        battleLog: [],
        duelWinner: "",
        duelLoser: ""     
    },
    {
        duelId: 4,
        isActive: true,
        stake: "",
        isCompleted: false,
        duelCreator: 'Nonso',
        avatar: "./assets/img/Rhyno.png",
        duelParticipant: '',
        creatorWarriors: [],
        participantWarriors: [],
        creatorStrategy: '',
        participantStrategy: '',
        battleLog: [],
        duelWinner: "",
        duelLoser: ""     
    },
    {
        duelId: 5,
        isActive: true,
        stake: "",
        isCompleted: false,
        duelCreator: 'N. West',
        avatar: "./assets/img/Rhyno.png",
        duelParticipant: '',
        creatorWarriors: [],
        participantWarriors: [],
        creatorStrategy: '',
        participantStrategy: '',
        battleLog: [],
        duelWinner: "",
        duelLoser: ""     
    },
    {
        duelId: 6,
        isActive: true,
        stake: "",
        isCompleted: false,
        duelCreator: 'Blaize',
        avatar: "./assets/img/Rhyno.png",
        duelParticipant: 'Janny',
        creatorWarriors: [],
        participantWarriors: [],
        creatorStrategy: '',
        participantStrategy: '',
        battleLog: [],
        duelWinner: "",
        duelLoser: ""
    },
    {
        duelId: 7,
        isActive: true,
        stake: "",
        isCompleted: true,
        duelCreator: 'Beast',
        avatar: "./assets/img/Rhyno.png",
        duelParticipant: 'Viking',
        creatorWarriors: [],
        participantWarriors: [],
        creatorStrategy: '',
        participantStrategy: '',
        battleLog: [],
        duelWinner: "Viking",
        duelLoser: "Beast"     
    },
    {
        duelId: 8,
        isActive: true,
        stake: "",
        isCompleted: false,
        duelCreator: 'Felis',
        avatar: "./assets/img/Rhyno.png",
        duelParticipant: '',
        creatorWarriors: [],
        participantWarriors: [],
        creatorStrategy: '',
        participantStrategy: '',
        battleLog: [],
        duelWinner: "",
        duelLoser: ""     
    }
]

export default data;