const data = [
    {
        id: 1,
        name: "Pikachu",
        img: "./assets/img/streamers01.png",
        health: 80,
        strength: 8,
        attack: 15,
        speed: 10,
        superPower: "Thunderbolt",
        totalWins: 270,
        totalLoss: 0,
        profileImg: "./assets/img/team01.png",
        price: 100,
        owner: ""        
    },
    {
        id: 2,
        name: "Charizard",
        img: "./assets/img/streamers02.png", 
        health: 95,
        strength: 10,
        attack: 13,
        speed: 7,
        superPower: "Flamethrower",
        totalWins: 390,
        totalLoss: 0,
        profileImg: "./assets/img/team04.png",
        price: 100,
        owner: "" 
    },
    {
        id: 3,
        name: "Bulbasaur", 
        img: "./assets/img/streamers03.png", 
        health: 60,
        strength: 5,
        attack: 10,
        speed: 8,
        superPower: "Vine Whip",
        totalWins: 250,
        totalLoss: 0,
        profileImg: "./assets/img/team03.png",
        price: 100,
        owner: "" 
    },
    {
        id: 4,
        name: "Squirtle", 
        img: "./assets/img/streamers04.png", 
        health: 90,
        strength: 10,
        attack: 16,
        speed: 9,
        superPower: "Water Gun",
        totalWins: 380,
        totalLoss: 0,
        profileImg: "./assets/img/team01.png",
        price: 100,
        owner: "" 
    },
    {
        id: 5,
        name: "Jigglypuff", 
        img: "./assets/img/streamers05.png",
        health: 75,
        strength: 7,
        attack: 13,
        speed: 9,
        superPower: "Sleep Song",
        totalWins: 300,
        totalLoss: 0,
        profileImg: "./assets/img/team02.png",
        price: 100,
        owner: "" 
    },
    {
        id: 6,
        name: "Mewtwo", 
        img: "./assets/img/streamers06.png",
        health: 90,
        strength: 12,
        attack: 16,
        speed: 6,
        superPower: "Psychic",
        totalWins: 380,
        totalLoss: 0,
        profileImg: "./assets/img/team03.png",
        price: 100,
        owner: "" 
    },
    {
        id: 7,
        name: "Eevee", 
        img: "./assets/img/streamers07.png",
        health: 100,
        strength: 11,
        attack: 15,
        speed: 7,
        superPower: "Adaptability",
        totalWins: 410,
        totalLoss: 0,
        profileImg: "./assets/img/team04.png",
        price: 100,
        owner: "" 
    },
    {
        id: 8,
        name: "Gengar", 
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXHD4t6CkRbhz_VPvRVqUKxA-6PaEuHlS9GKaKguu-B1F0weSMnjPXkgRUQppt7bKou7M&usqp=CAU",
        health: 100,
        strength: 12,
        attack: 15,
        speed: 6,
        superPower: "Shadow Ball",
        totalWins: 420,
        totalLoss: 0,
        profileImg: "./assets/img/team04.png",
        price: 100,
        owner: ""
    }
]

export default data;